export const InternalError = createError({
  statusCode: 500,
  message: "An unexpected error has occurred",
});
